

export const PUBLIC_SUPABASE_URL = 'https://zougcsomgqnfumqkwuoj.supabase.co';
export const PUBLIC_SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdWdjc29tZ3FuZnVtcWt3dW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4OTg0NDgsImV4cCI6MjA5NzQ3NDQ0OH0.71u1D-lfjDDNllg_pRj8hoqcq1vP2tGhFQ624XUoVrs';
